spring:
  cloud:
    gateway:
      routes:
        - id: filmModule
          uri: https://film-microservice-challenge8.up.railway.app/
          predicates:
            - Path=/films/**, /schedules/**
        - id: userModule
          uri: https://user-microservice-challenge8.up.railway.app/
          predicates:
            - Path=/users/**, /api/auth/**
        - id: seatModule
          uri: https://seat-microservice-challenge8.up.railway.app/
          predicates:
            - Path=/seats/**
        - id: invoiceModule
          uri: https://invoice-microservice-challenge8.up.railway.app/
          predicates:
            - Path=/invoice/**
        - id: kafkaModule
          uri: https://kafka-microservice-challenge8.up.railway.app/
          predicates:
            - Path=/post-message
